version: "3.1"

services:
  # MongoDB + GUI Manager
  mongo:
    image: mongo:3.6
    container_name: gql-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - ./data/mongodb:/data/db
    ports:
      - 27017:27017

  # https://hub.docker.com/_/mongo-express/
  mongo-express:
    image: uchilaka/mongo-express
    build:
      context: ./apps/mongo-express
    container_name: gql-mongo-ui
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test
    depends_on:
      - mongo

  # MySQL DB + GUI Manager
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: gql-mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  mysql-admin:
    image: adminer
    container_name: gql-mysql-admin
    restart: unless-stopped
    ports:
      - 8091:8080
    depends_on:
      - mysql
